
name: manovecina
description: "ManoVecina Flutter client"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  geolocator: ^12.0.0
  firebase_core: ^2.24.2
  firebase_messaging: ^14.9.0
  flutter_local_notifications: ^17.1.0
  cloud_firestore: ^4.15.2
  firebase_storage: ^11.6.0
  supabase_flutter: ^2.5.0  # Nueva dependencia para Supabase
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  photo_view: ^0.14.0
  shimmer: ^3.0.0
  path: ^1.9.0  # Para manejo de rutas de archivos
  universal_html: ^2.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
